### ISSUE TITLE
Responsive images en slider

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-01#3]
- Genial el slider!! Lo único que la imagen no es responsive. Traten de que su tamaño no se distorsione con el cambio de tamaño de la pantalla. 

https://github.com/1022FSNSANCN02ARED/grupo-01/blob/980582786c8540ed0f96f82c910283b16de0048e/public/css/styles.css#L180

**Comment by Natalia-3105** [comment]
Ya se soluciono.
