### ISSUE TITLE
CSS sobrante

### ISSUE THREAD

**Issue by LuiosDyet** [1022FSNSANCN02ARED/grupo-01#4]
Piensan usar muchos tabs? Imagino que deben haber copiado el CSS de algún lado, capaz si sólo van a usar 2 tabs podrían limpiar las reglas de CSS que no se usan. 

https://github.com/1022FSNSANCN02ARED/grupo-01/blob/980582786c8540ed0f96f82c910283b16de0048e/public/css/styles_login.css#L13-L20

**Comment by Miguel101177** [comment]
En principio se había dejado ese bloque de lógica con varios tabs pensando en poder reutilizar el mismo a futuro en otras secciones.
Igualmente controlaremos la lógica para buscar y limpiar lo que no se use.
Gracias.
